<?php
$menuStack = 'menu';
?>
<ul class="dropdown-menu">
    <?php
    foreach ($container as $page):
        if (!$this->navigation()->accept($page)) {
            continue; 
        }
        /* @var $page Zend\Navigation\Page\Mvc */
        $hasChildren = $page->hasPages();
        if (!$hasChildren): 
            $target = $page->getTarget() ? 'target="' . $page->getTarget() . '"' : NULL;
            $active = $page->isActive() ? ' class="active"' : NULL;
            $icon = $page->get("icon") !== "" ? $page->get("icon") : NULL;
            ?>
            <li<?php echo $active ?>>
                <a class="nav-header" href="<?php echo $page->getHref() ?>" <?php echo $target ?>>
                    <?php if ($icon) : ?>
                        <span class="<?php echo $icon; ?>"></span>
                    <?php endif; ?>
                    <?php echo $page->getLabel() ?>
                </a>
            </li>
        <?php 
        else: 
            //check if access is allowed at least one item
            $access = false;
            foreach ($page->getPages() as $child) {
                if ($this->navigation()->accept($child) && $child->get("separator") !== true) {
                    $access = true;
                }
            }
            if ($access) :        
                $target = $page->getTarget() ? 'target="' . $page->getTarget() . '"' : NULL;
                $active = $page->isActive() ? ' active' : NULL;
                $icon = $page->get("icon") !== "" ? $page->get("icon") : NULL;
                ?> 
                <li class="dropdown<?php echo $active ?>">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <?php if ($icon): ?>
                            <span class="<?php echo $icon; ?>"></span>
                        <?php endif; ?>
                        <?php echo $page->getLabel() ?>
                        <b class="glyphicon-circle-arrow-right"></b>
                    </a>
                    <?php echo $this->partial('navigation/submenu',array('container' => $page->getPages(), 'menuStack' => $menuStack)); ?>
                    
                </li>   
            <?php endif; ?>
        <?php endif ?>
    <?php endforeach ?>
</ul>